# .github/workflows/tests.yml

name: Tests Jest

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Utiliser Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Installer package.json
      run: npm install
    - name: Lancer les tests
      run: npm test